[package]
name = "bevy_new_third_person" # ToDo
version = "0.1.0"
publish = false
authors = ["Oleks Pickle <22867443+olekspickle@users.noreply.github.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
exclude = ["dist", "build", "assets", "credits"]
repository = "https://github.com/olekspickle/bevy_new_third_person"
description = "Simple opinionated third person view 3D game template"

[workspace]
members = ["mobile"]

[features]
default = [
    # Default to a native dev build.
    "dev_native",
]
dev = [
    # Improve compile times for dev builds by linking Bevy as a dynamic library.
    "bevy/dynamic_linking",
    "bevy/bevy_dev_tools",
    # "bevy-inspector-egui",
    # "avian2d/debug-plugin",
]
dev_native = [
    "dev",
    # Enable asset hot reloading for native dev builds.
    "bevy/file_watcher",
    # Enable embedded asset hot reloading for native dev builds.
    "bevy/embedded_watcher",
]
physics_debug = []

[dependencies]
bevy = { version = "0.15", features = ["wayland"] }
bevy_common_assets = {version="0.12.0", features=["ron"]}
bevy_third_person_camera = "0.2.0"
bevy_atmosphere = "0.12.2"
bevy-tnua = "0.21.0"
bevy-tnua-avian3d = "0.2.0"
avian3d = "0.2.1"
image = { version = "0.25", default-features = false }
iyes_perf_ui = "0.4.0"
leafwing-input-manager = "0.16.0"
## This greatly improves WGPU's performance due to its heavy use of trace! calls
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
rand = { version = "0.8.3" }
serde = "1"
# keep the following in sync with Bevy's dependencies
winit = { version = "0.30", default-features = false }

[lints.clippy]
# Bevy supplies arguments to systems via dependency injection, so it's natural for systems to
# request more than 7 arguments, which would undesirably trigger this lint.
too_many_arguments = "allow"
# Queries may access many components, which would undesirably trigger this lint.
type_complexity = "allow"
# Make sure macros use their standard braces, such as `[]` for `bevy_ecs::children!`.
nonstandard_macro_braces = "warn"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

# This is used by trunk as it doesn't support custom profiles: https://github.com/trunk-rs/trunk/issues/605
# xbuild also uses this profile for building android AABs because I couldn't find a configuration for it
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

# Profile for distribution
[profile.dist]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
strip = true

[build-dependencies]
embed-resource = "1"
