[tasks]
clean = { command = "cargo", args = ["clean"] }
build = { command = "cargo", args = ["build"] }
fmt = { command = "cargo", args = ["fmt", "--all", "--", "--check"] }
doc = { command = "cargo", args = ["doc", "--locked", "--profile","ci", "--document-private-items", "--no-deps"] }
clippy = { command = "cargo", args = ["clippy", "--all-targets", "--", "-D", "warnings"] }
lint = { dependencies = ["clippy", "fmt", "doc"] }
clean-build = { dependencies = ["clean", "build", "lint"] }

[tasks.check-web]
command = "cargo"
args = ["check", "--profile", "ci", "--no-default-features", "--features", "web", "--target", "wasm32-unknown-unknown"]

[tasks.install-wasm-deps]
command = "cargo"
args = ["binstall", "--locked", "-y", "--force", "wasm-bindgen-cli", "wasm-opt"]

[tasks.build-web]
command = "bevy"
args = ["build", "--locked", "--release", "--no-default-features", "--features=web", "--yes", "web", "--bundle"]

[tasks.web]
command = "bevy"
args = ["run", "--release", "--no-default-features", "--features", "web", "web", "-U", "multi-threading"]

[tasks.hot]
install_crate = "dioxus-cli"
command = "dx"
args = ["serve", "--hot-patch", "--features", "dev_native"]

[tasks.tracy]
command = "cargo"
args = ["run", "--features", "debug", "--release"]

