# # CRANELIFT speedup: https://bevy.org/learn/quick-start/getting-started/setup/#cranelift
# [unstable]
# build-std = ["std", "core", "alloc", "panic_abort"]
# codegen-backend = true
# [profile.dev]
# codegen-backend = "cranelift"
# # Consider compiling deps with llvm for runtime perf and working `#[should_panic]`
# # If you don't have any tests that `#[should_panic]`, comment this out for *massive* speedups
# # For me, it makes a 16 minute build take 6 minutes.
# [profile.dev.package."*"]
# codegen-backend = "llvm"
# [profile.release] # Disable cranelift for release profile
# codegen-backend = "llvm"
# [profile.web] # cranelift cannot build wasm32-unknown-unknown out of the box
# codegen-backend = "llvm"

# # nightly linker speedup
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = [
#     "-Clink-arg=-fuse-ld=mold",
#     "-Zshare-generics=y",
#     "-Zthreads=0",
# ]
# rustdocflags = [
#     "-Zshare-generics=y",
#     "-Zthreads=0",
# ]

[target.wasm32-unknown-unknown]
rustflags = [
    "-Ctarget-feature=+atomics",
    "-Clink-arg=--shared-memory",
    "-Clink-arg=--max-memory=1073741824",
    "-Clink-arg=--import-memory",
    "-Clink-arg=--export=__wasm_init_tls",
    "-Clink-arg=--export=__tls_size",
    "-Clink-arg=--export=__tls_align",
    "-Clink-arg=--export=__tls_base",
]
# Nightly
# rustdocflags = [
#     "-Zshare-generics=y",
#     "-Zthreads=0",
#     "-Clink-arg=-fuse-ld=mold",
# ]


# BUILD
[profile]
incremental = true

[package.metadata.bevy_cli.release] # Disable dev features for release builds.
default-features = false
[package.metadata.bevy_cli.web]     # Disable native features for web builds.
default-features = false
[package.metadata.bevy_cli.web.dev]
features = ["dev"]

[profile.dev]                       # Less optimization in the dev profile.
opt-level = 1
[profile.dev.package."*"]           # More optimization in the dev profile for dependencies.
opt-level = 3
[profile.dev.package.wgpu-types]    # Remove expensive debug assertions due to <https://github.com/bevyengine/bevy/issues/14291>
debug-assertions = false

[profile.ci]                        # Optimize for build time in CI.
inherits = "dev"
opt-level = 0
debug = "line-tables-only"
codegen-units = 4
[profile.ci.package."*"]
opt-level = 0

[profile.release]
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Compile the entire crate as one unit. Slows compile times to less size.
# Default is 16 or 256(incremental builds). This template f.e. 18Mb -> 24Mb
codegen-units = 1
strip = true

[profile.web]
inherits = "release"
strip = "debuginfo"                 # Strip all debugging information from the binary to slightly reduce file size.

